# Generated by Django 2.2.3 on 2019-07-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parse_url', models.SlugField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(max_length=500)),
            ],
        ),
    ]
