# Generated by Django 2.2.3 on 2019-09-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('delete_on', models.DateTimeField(blank=True, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('propscheduleid', models.CharField(max_length=10)),
                ('orgcode', models.CharField(max_length=10)),
                ('destcode', models.CharField(max_length=10)),
                ('orgid', models.IntegerField()),
                ('desid', models.IntegerField()),
                ('noka', models.CharField(max_length=10)),
                ('subclass', models.CharField(max_length=10)),
                ('subclassid', models.IntegerField()),
                ('wagonclasscode', models.CharField(choices=[('EKO', 'Ekonomi'), ('BIS', 'Bisnis'), ('EKS', 'Eksekutif')], default='EKO', max_length=10)),
                ('wagonclassid', models.IntegerField()),
                ('trainname', models.CharField(max_length=100)),
                ('tripid', models.CharField(max_length=10)),
                ('arrivaldatetime', models.DateTimeField()),
                ('departdatetime', models.DateTimeField()),
                ('stationnameorg', models.CharField(max_length=50)),
                ('stationnamedest', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
