# Generated by Django 2.2.3 on 2019-09-11 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kai2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('delete_on', models.DateTimeField(blank=True, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Open Booking'), (2, 'Waiting List'), (3, 'Waiting Payment'), (4, 'Paid'), (5, 'Finish'), (9, 'Drop')], default=1)),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkin', to='kai2.Checkin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('delete_on', models.DateTimeField(blank=True, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('passenger_nm', models.CharField(max_length=50)),
                ('passenger_identity', models.CharField(max_length=30)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='kai2.Booking')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
