# Generated by Django 2.2.3 on 2019-07-17 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('delete_on', models.DateTimeField(blank=True, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('quote_id', models.CharField(default='New', editable=False, max_length=5)),
                ('dep_code', models.CharField(max_length=10)),
                ('des_code', models.CharField(max_length=10)),
                ('departure_date', models.DateField()),
                ('train_code', models.CharField(max_length=10)),
                ('subclass', models.CharField(max_length=2)),
                ('genre', models.PositiveSmallIntegerField(choices=[(1, 'Mr'), (2, 'Mrs')], default=1)),
                ('name', models.CharField(max_length=100)),
                ('id_card', models.CharField(max_length=30)),
                ('closed', models.BooleanField(default=False)),
                ('expired_on', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
