# Generated by Django 2.2.3 on 2019-07-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kai', '0002_auto_20190717_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'In Progress'), (2, 'Catched'), (0, 'Closed')], default=1),
        ),
    ]
