# Generated by Django 2.2.3 on 2019-07-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kai', '0003_auto_20190717_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='telegram',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
