# Generated by Django 2.2.3 on 2019-07-26 07:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kai', '0005_quotation_last_record_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('delete_on', models.DateTimeField(blank=True, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('book_code', models.CharField(blank=True, max_length=20)),
                ('arrival_code', models.CharField(blank=True, max_length=10)),
                ('arrival_name', models.CharField(blank=True, max_length=255)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('depart_code', models.CharField(blank=True, max_length=10)),
                ('depart_name', models.CharField(blank=True, max_length=255)),
                ('depart_time', models.DateTimeField(blank=True, null=True)),
                ('book_balance', models.IntegerField(default=0)),
                ('book_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_name', models.CharField(blank=True, max_length=50)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('discount', models.IntegerField(default=0)),
                ('extra_fee', models.IntegerField(default=0)),
                ('normal_sales', models.IntegerField(default=0)),
                ('admin_fee', models.IntegerField(default=0)),
                ('pay_code', models.CharField(blank=True, max_length=50)),
                ('pass_name', models.CharField(blank=True, max_length=200)),
                ('pass_id', models.CharField(blank=True, max_length=50)),
                ('seat_num', models.CharField(blank=True, max_length=10)),
                ('seat_name', models.CharField(blank=True, max_length=50)),
                ('wagon', models.CharField(blank=True, max_length=5)),
                ('train_name', models.CharField(blank=True, max_length=200)),
                ('train_code', models.CharField(blank=True, max_length=10)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_order', to='kai.Quotation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
