# Generated by Django 2.2.3 on 2019-07-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kai', '0006_trainorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainorder',
            name='payment_time_limit_str',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='trainorder',
            name='payment_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
