# Generated by Django 2.2.3 on 2019-07-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kai', '0007_auto_20190726_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainorder',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Waiting Payment'), (0, 'Paid'), (2, 'Expired')], default=1),
        ),
    ]
