# Generated by Django 2.2.3 on 2019-07-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kai', '0008_trainorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainorder',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Open'), (2, 'Waiting Payment'), (0, 'Paid'), (9, 'Expired')], default=1),
        ),
    ]
