# Generated by Django 2.2.3 on 2019-07-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kai', '0009_auto_20190726_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainorder',
            name='unix_code',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
