# Generated by Django 2.2.3 on 2019-07-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kai', '0010_trainorder_unix_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'In Progress'), (3, 'Detected'), (2, 'Catched'), (0, 'Closed')], default=1),
        ),
    ]
